pipeline:
  name: test_ank
  identifier: test_ank
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: bit_bucket_test
        identifier: bit_bucket_test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "abc"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
